### ISSUE TITLE
Make city selection better

### ISSUE THREAD

**Issue by Fohlen** [eventzimmer/site#11]
It should be possible for the user to select a nearby city (or his own city).

- [ ] Check if location has previously been set
- [ ] Get latitude / longitude using https://ipinfo.io/ (privacy?)
- [ ] Load nearest cities using latitude / longitude
- [ ] Offer zipcode search
- [ ] Offer name search

**Comment by acdpsn** [comment]
Can I work on this? I think you can use the web browser to get user location instead of using their IP, plus they can decline sharing it to preserve privacy.

**Comment by Fohlen** [comment]
Hey @akim8

Yes this is a viable option, in fact a previous version of eventzimmer has been using the `geolocation` api.
However using the `geolocation` API on page load [is considered a bad practice](https://developers.google.com/web/tools/lighthouse/audits/geolocation-on-load).

So any option to use the `geolocation` API should/must involve the user clicking on a location element.

Do you think we can build a good user experience out of this and would like to tackle the issue?

Greetings from ☀️south of Germany!

**Comment by Fohlen** [comment]
As [city analysis](https://cityanalysis-anonnorrcw.notebooks.azure.com/j/notebooks/analysis.ipynb) reveals, we currently have four highly frequented cities, so including them in a `JSON` makes sense. See 
![download](https://user-images.githubusercontent.com/3730888/67150934-845e6e80-f2be-11e9-91c6-7f0385e68ae1.png)
