### ISSUE TITLE
Do not overlap the footer of the main site with the back-to-top button

### ISSUE THREAD

**Issue by Fohlen** [eventzimmer/site#22]
This happens on mobile, when you scroll down to the bottom of the page, effectively making the Instagram link unusable.

**Comment by iryb** [comment]
I can make footer font size on mobile smaller, then both button and footer will fit perfectly. Can I work on this issue?

**Comment by Fohlen** [comment]
Hey @burianovata 
First of all thanks for contributing :clinking_glasses: 

There is two ways to tackle this problem:

- try `@media` queries to have the button fit perfectly on mobile (I believe this requires a lot of effort)
- hide the button when it leaves the `main` element (in the source code, https://github.com/eventzimmer/site/blob/master/src/App.vue#L39 )

So the decision is up to you! I'd very much appreciate a nice looking solution.

PS: I have an old 4 inch phone. If you need to test on a really small screen, let me know.
