### ISSUE TITLE
Remove jQuery if possible

### ISSUE THREAD

**Issue by Fohlen** [eventzimmer/site#23]
Take care of the code that handles the `back-to-top` button

**Comment by iryb** [comment]
Hey! Do you want to remove this button at all? I guess it won't be appearing properly without jQuery (on scroll).

**Comment by Fohlen** [comment]
Hey @burianovata 

I just checked the respective code. Apparently I have done this before. Instead of `$.scroll(...)` you can use `window.onscroll` as well. See https://github.com/eventzimmer/site/blob/master/src/App.vue#L39

You can however, remove `jQuery` from the `index.html`, `impress.html` and `privacy.html` and check if the page still behaves accordingly. Make a PR and I'll merge happily!

**Comment by Fohlen** [comment]
Closed by c60fac7b7cf4571fd358b8099756660b31fed6a7
