### ISSUE TITLE
Do not add a read-more button if there is not enough text

### ISSUE THREAD

**Issue by Fohlen** [eventzimmer/site#24]
Currently the read-more button is always shown.

**Comment by BarnikRay** [comment]
I would like to work on this issue

**Comment by Fohlen** [comment]
Hey @BarnikRay 

Thanks for helping out 🥂 

The code for the button can be found here: https://github.com/eventzimmer/site/blob/master/src/components/Event.vue#L15

If you have not worked with [Vue Single File Component's](https://vuejs.org/v2/guide/single-file-components.html) yet, I suggest you have a look at the Vue.js documentation.

To get you started:

- clone the repository
- `npm i`
- `VUE_APP_ENDPOINT=https://api.eventzimmer.de npm run serve` (this sets the backend to be `api.eventzimmer.de`)

You will most likely need to add a `v-if` to the button. Once done, please also verify that `npm run lint` runs through. 

I look forward to review your PR. If you have questions feel free to use this tracker.

**Comment by BarnikRay** [comment]
Thanks so much for the details.. I'll work on it and get back to you if I need anything..

**Comment by Fohlen** [comment]
Hey @BarnikRay 
Sorry to inform you that this issue has been closed by @dialmedu with https://github.com/eventzimmer/site/pull/27

You may try one of the other issues of course!
