### ISSUE TITLE
Redesign event cards

### ISSUE THREAD

**Issue by Fohlen** [eventzimmer/site#25]
They should be more conceivable, it is too much text.

See e.g:

- [Bootstrap list snippet](https://jsfiddle.net/bootstrapious/dh9bt7up)
- [Facebook events](https://www.facebook.com/pg/ICFATuebingen/events/?ref=page_internal) especially on mobile!

**Comment by Sbaah** [comment]
Hello, I would like to attempt this.

**Comment by Fohlen** [comment]
Hey @Sbaah thanks for tackling this issue ✨ 
Here are my two cents what is really important:

- the information should be as easy to process as possible (show date, location, name)
- it should spark some excitement in the user (maybe use the tags)
- when clicking it should provide full text
- the backlink (to `event.url`) **must** be clickable at all times (because of copyright)

The code for the event component can be found here: https://github.com/eventzimmer/site/blob/master/src/components/Event.vue

I just updated the `README` so it has all the important details for getting up and running.
Once done, please also have a look at the [contributions guideline](https://github.com/eventzimmer/schema/blob/master/CONTRIBUTING.md).

If you have any question I'd be happy to respond here.

**Comment by Fohlen** [comment]
Hey @Sbaah, haven't heard of you in a while. Do you need any help to get this started?

**Comment by Sbaah** [comment]
Sorry, but i have being reading up on Vue to try understand it and how it relate to your code.
Also i wont be able to get to it  week, for I have a midterm exams going.

**Comment by Sbaah** [comment]
Hello @Fohlen  all the requirement you asked for already exit in the web app.
I don't what else i could add for it to be a "Redesign event cards"
Run your code tested it out ...
[Screen Recording 2019-10-19 at 4.22.35 PM.mov.zip](https://github.com/eventzimmer/site/files/3747153/Screen.Recording.2019-10-19.at.4.22.35.PM.mov.zip)

**Comment by Fohlen** [comment]
Hey @Sbaah yes technically the events meet the requirements. However it's not very pretty. There is a **lot** of text, distracting from the event titles. Facebook did solve this much better (usability). See attached photo:

<img width="1440" alt="facebook" src="https://user-images.githubusercontent.com/3730888/67151112-40b93400-f2c1-11e9-95e8-377c6f27ff4a.png">

I would like the event cards to have less text so it is easier to read them (and only expand text when the user is actually interested). I hope my idea is now a bit clearer to you!

Let me know if you think we could make the user experience better in this regard.

**Comment by Sbaah** [comment]
Will come thing like this be ok?
![Screen Shot 2019-10-19 at 4 46 37 PM](https://user-images.githubusercontent.com/19510118/67151195-274bc400-f290-11e9-9df1-b4f3b64abf29.png)
 or you want some like a card within a card ... i believe that what Facebook is doing.

**Comment by Fohlen** [comment]
Closed with #51

Thanks @Sbaah for the work and inspiration. You should add yourself to the [CONTRIBUTORS](https://github.com/eventzimmer/.github/blob/master/CONTRIBUTORS.md) list!
