### ISSUE TITLE
Set default language

### ISSUE THREAD

**Issue by Fohlen** [eventzimmer/site#34]
Currently `de` is the default locale choice. It would be good to respect the [`language`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language) property when no locale is set.

**Comment by VivekSingh777** [comment]
@Fohlen Can i try this one

**Comment by Fohlen** [comment]
Hey @VivekSingh777 yes it is still open. Have a look at the [store](https://github.com/eventzimmer/site/blob/master/src/store.js#L30). I would set this to `null` by default and update it in `main.js` at the first start. Looking forward for your ideas ✨

**Comment by VivekSingh777** [comment]
@Fohlen navigator.language will return `en-GB` like values not `en`

**Comment by Fohlen** [comment]
@VivekSingh777 I believe `navigator.language.substring(0, 2)` is sufficient. There is no plan to support *very* specific locales, such as british vs american.

**Comment by Fohlen** [comment]
Closed by #37
