### ISSUE TITLE
Refactor selection module into seperate file

### ISSUE THREAD

**Issue by Fohlen** [eventzimmer/site#35]
Currently the `store.js` contains the `selection` module. This should be separated into a dedicated file. 

- [ ] Create a `store` folder
- [ ] Move `selection` into `store/selection.js`
- [ ] Move everything else into `store/index.js`

**Comment by poojakp94** [comment]
@Fohlen I would like to help you with this.

**Comment by Fohlen** [comment]
Hey @poojakp94 
Thanks for taking this on 🍔 

Let me know if you need any further hints.
Greetings from Vienna 🇦🇹

**Comment by poojakp94** [comment]
Hey @Fohlen I have submitted a pull request for this.
 Please let me know if it needs any further changes.

Greetings from India 🇮🇳 😊
